import { apiRequest, newIdempotencyKey, ApiError } from "@/lib/api/client"

export type Pricing = { size_tiers: Array<{ code: string; display_name: string; max_mcq_count: number; max_cq_count: number; price_amount: number; currency: string }>; paper_entitlement_packages: Array<{ code: string; display_name: string; size_tier_code: string; quantity: number; price_amount: number; currency: string }>; features: Array<{ code: string; name: string; description: string }>; template_extraction_standalone_price: number; template_extraction_currency: string }
export type Entitlements = { features: Array<{ feature_code: string; feature_name: string; trial_available: boolean; trial_consumed: boolean; purchased_available_count: number; granted_available_count: number }>; paper_export: Array<{ size_tier_code: string; available_count: number }> }
export type Readiness = { tier_code: string; tier_display_name: string; price_amount: number; currency: string; mcq_count: number; cq_count: number; question_count: number; requires_entitlement: boolean; has_available_entitlement: boolean; can_export_now: boolean }
export function isPaymentsEnabled() { return (process.env.NEXT_PUBLIC_PAYMENTS_MODE ?? "disabled") === "mock" }

export const billingApi = { pricing: () => apiRequest<Pricing>("/api/v1/billing/pricing"), entitlements: () => apiRequest<Entitlements>("/api/v1/billing/entitlements"), readiness: (id: string) => apiRequest<Readiness>(`/api/v1/papers/${id}/export-readiness`), jobs: () => apiRequest<{ items: Array<{ id: string; job_type: string; status: string; created_at: string }> }>("/api/v1/jobs?page_size=10"), purchase: (kind: "paper-export" | "template-extraction", packageCode?: string) => apiRequest<{ purchase: { id: string; amount: number; currency: string }; payment: { id: string; status: string }; provider_payload?: { redirect_url?: string } }>(`/api/v1/billing/purchases/${kind}`, { method: "POST", headers: { "Idempotency-Key": newIdempotencyKey() }, body: JSON.stringify(packageCode ? { package_code: packageCode } : {}) }), mockWebhook: (purchaseId: string, status: "succeeded" | "failed") => apiRequest(`/api/v1/billing/payments/mock-webhook`, { method: "POST", body: JSON.stringify({ purchase_id: purchaseId, provider_reference: `mock-${newIdempotencyKey()}`, status }) }) }
export function money(amount: number, currency = "BDT") { return `${currency === "BDT" ? "৳" : currency} ${amount.toLocaleString()}` }
export function billingError(error: unknown) { if (error instanceof ApiError && error.code === "PAPER_EXCEEDS_MAXIMUM_TIER") return "This paper is too large to export. Remove some questions."; if (error instanceof ApiError && error.code === "PAPER_HAS_NO_QUESTIONS") return "Add at least one question first."; return error instanceof Error ? error.message : "Something went wrong. Please try again." }
