import { apiRequest, fetchBlob, newIdempotencyKey } from "@/lib/api/client"

export type TemplateStatus = "pending" | "extracting" | "ready" | "failed" | "archived"
export type TemplateSummary = { id: string; name: string; status: TemplateStatus; version: number; root_template_id: string | null; previous_version_id: string | null; source_file_asset_id: string; logo_file_asset_id: string | null; watermark_file_asset_id: string | null; error_message: string | null; created_at: string }
export type TemplateDetail = TemplateSummary & { structure: { page: { width_mm: number; height_mm: number; orientation: "portrait" | "landscape"; margins: Record<string, number>; columns: { count: number; spacing_mm: number } }; header: { present: boolean; linked_to_previous: boolean; blocks: Array<{ text?: string }>; images: ImageRef[] }; footer: { present: boolean; linked_to_previous: boolean; blocks: Array<{ text?: string }>; images: ImageRef[] }; watermark: { present: boolean; kind: "text" | "image" | "none"; text: string | null; image_file_asset_id: string | null; rotation_degrees: number; color_hex: string | null }; body: { blocks: Array<{ text?: string }>; slots: Array<{ slot_type: string; block_order_index: number; notes?: string | null }>; images: ImageRef[] }; fonts: string[]; styles: Array<{ name?: string }>; numbering: Array<Record<string, unknown>>; unmapped_ooxml_notes: string[] } }
export type ImageRef = { file_asset_id: string; width_mm: number; height_mm: number; kind: "logo" | "watermark" | "figure" | "unknown"; location: "header" | "footer" | "body" }
const base = () => (process.env.NEXT_PUBLIC_API_BASE_URL ?? "").replace(/\/$/, "")
async function multipart(path: string, file: File, name?: string) { const form = new FormData(); form.append("file", file); if (name !== undefined) form.append("name", name); const response = await fetch(`${base()}${path}`, { method: "POST", body: form, credentials: "include", headers: { Authorization: `Bearer ${(await import("@/lib/api/auth")).authTokenStore.accessToken ?? ""}`, "Idempotency-Key": newIdempotencyKey() } }); if (!response.ok) throw await (await import("@/lib/api/client")).toApiError(response); return response.json() as Promise<TemplateDetail> }
export const templatesApi = { list: (includeArchived = false) => apiRequest<{ items: TemplateSummary[]; pagination?: unknown }>(`/api/v1/templates?page=1&page_size=100&include_archived=${includeArchived}`), get: (id: string) => apiRequest<TemplateDetail>(`/api/v1/templates/${id}`), upload: (file: File, name: string) => multipart("/api/v1/templates", file, name), version: (id: string, file: File, name?: string) => multipart(`/api/v1/templates/${id}/versions`, file, name), archive: (id: string) => apiRequest<TemplateSummary>(`/api/v1/templates/${id}`, { method: "DELETE" }), image: (id: string) => fetchBlob(`/api/v1/files/${id}/content`) }
export const billingApi = { pricing: () => apiRequest<{ template_extraction_standalone_price: number; template_extraction_currency: string }>("/api/v1/billing/pricing"), purchaseTemplateExtraction: () => apiRequest("/api/v1/billing/purchases/template-extraction", { method: "POST", body: "{}", headers: { "Idempotency-Key": newIdempotencyKey() } }) }
export function templateUses(entitlements: { features?: Array<{ feature_code: string; trial_available: boolean; purchased_available_count: number; granted_available_count: number }> } | undefined) { const feature = entitlements?.features?.find((item) => item.feature_code === "template_extraction"); return feature ? (feature.trial_available ? 1 : 0) + feature.purchased_available_count + feature.granted_available_count : 0 }
