"use client"
import useSWR from "swr"
import { useState } from "react"
import { PageContainer, PageHeader } from "@/components/shell/page-header"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { billingApi, money } from "@/lib/api/billing"
import { CheckoutSheet } from "@/components/billing/checkout-sheet"
export default function PricingPage(){const {data}=useSWR("billing-pricing",billingApi.pricing);const [checkout,setCheckout]=useState<{kind:"paper_export"|"template_extraction";code?:string}|null>(null);return <PageContainer><PageHeader title="Pricing" description="Simple one-time purchases for papers and teacher tools."/><p className="text-sm text-muted-foreground">Paper size is decided by how many multiple-choice and creative questions the paper has — never by hidden weights.</p><div className="grid gap-4 md:grid-cols-3">{data?.size_tiers.map(tier=><Card key={tier.code}><CardHeader><CardTitle>{tier.display_name}</CardTitle><CardDescription>Up to {tier.max_mcq_count} multiple-choice questions, or {tier.max_cq_count} creative question{tier.max_cq_count===1?"":"s"}.</CardDescription></CardHeader><CardContent><p className="text-2xl font-semibold">{money(tier.price_amount,tier.code?"BDT":"BDT")}</p><p className="mt-1 text-sm text-muted-foreground">to export</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Paper export bundles</CardTitle><CardDescription>A bundle only applies to papers of its listed size.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{data?.paper_entitlement_packages.map(pkg=><div key={pkg.code} className="flex items-center justify-between gap-3 rounded-md border p-3"><div><p className="font-medium">{pkg.display_name}</p><p className="text-sm text-muted-foreground">{money(pkg.price_amount)} · {pkg.quantity} paper{pkg.quantity===1?"":"s"}</p></div><Button variant="outline" onClick={()=>setCheckout({kind:"paper_export",code:pkg.code})}>Buy</Button></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Template extraction</CardTitle><CardDescription>Copy a paper&apos;s design into a reusable template.</CardDescription></CardHeader><CardContent className="flex items-center justify-between gap-3"><span className="text-xl font-semibold">{data?money(data.template_extraction_standalone_price):"Loading…"}</span><Button variant="outline" onClick={()=>setCheckout({kind:"template_extraction"})}>Buy extraction</Button></CardContent></Card><p className="text-sm font-medium">Papers made only from the question bank export free.</p>{data?.features.map(feature=><div key={feature.code} className="rounded-md border p-3"><p className="font-medium">{feature.name}</p><p className="text-sm text-muted-foreground">One use means {feature.description}</p></div>)}{checkout?<CheckoutSheet open onOpenChange={(open)=>!open&&setCheckout(null)} kind={checkout.kind} packageCode={checkout.code} pricing={data} />:null}</PageContainer>}
