'use client'

import useSWR from 'swr'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { adminApi, adminQuery, type AdminRow } from '@/lib/api/admin'

const config = { entitlements: ['features', 'Feature entitlements'], 'paper-entitlements': ['paper-export', 'Paper export entitlements'], purchases: ['purchases', 'Purchases & payments'], operations: ['exports', 'Export records'], jobs: ['jobs', 'Jobs'], usage: ['usage', 'Provider usage'], templates: ['templates', 'Templates'], 'audit-log': ['audit', 'Audit log'] } as const
export function AdminTable({ kind }: { kind: keyof typeof config }) { const search = useSearchParams(); const [endpoint, title] = config[kind]; const params = Object.fromEntries(search.entries()); const query = adminQuery(params); const fetcher = () => endpoint === 'features' || endpoint === 'paper-export' ? adminApi.entitlements(endpoint, query) : endpoint === 'purchases' ? adminApi.purchases(query) : endpoint === 'exports' ? adminApi.exports(query) : endpoint === 'jobs' ? adminApi.jobs(query) : endpoint === 'usage' ? adminApi.usage(query) : endpoint === 'templates' ? adminApi.templates(query) : adminApi.audit(query); const { data, error, isLoading } = useSWR(`admin-${kind}${query}`, fetcher); const rows = data?.items ?? []; return <Card><CardHeader className="flex flex-col gap-3 border-b sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>{title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">Server-paginated, filterable, and read from `/api/v1/admin`.</p></div><Input defaultValue={params.q || ''} placeholder="Filter or search…" className="max-w-xs" /></CardHeader><CardContent className="p-0">{error ? <div className="p-6 text-sm text-destructive">{error.message}</div> : isLoading ? <div className="p-6 text-sm text-muted-foreground">Loading records…</div> : rows.length === 0 ? <div className="p-10 text-center text-sm text-muted-foreground">No records match these filters.</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 border-b bg-background"><tr><th className="px-4 py-3 font-medium">ID</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Details</th><th className="px-4 py-3 font-medium">Created</th></tr></thead><tbody>{rows.map((row: AdminRow) => <tr key={row.id} className="border-b last:border-0"><td className="px-4 py-3 font-mono text-xs"><Link href={kind === 'templates' ? `/templates/${row.id}` : `/admin/${kind}/${row.id}`} className="underline-offset-4 hover:underline">{row.id}</Link></td><td className="px-4 py-3"><Badge variant="outline">{String(row.status ?? row.action ?? 'record')}</Badge></td><td className="max-w-md truncate px-4 py-3 text-muted-foreground">{String(row.email ?? row.feature_code ?? row.job_type ?? row.entity_type ?? row.provider_name ?? row.name ?? '—')}</td><td className="px-4 py-3 text-muted-foreground">{String(row.created_at ?? row.occurred_at ?? '—')}</td></tr>)}</tbody></table></div>}<div className="flex items-center justify-between border-t p-4 text-xs text-muted-foreground"><span>{data?.pagination?.total_items ?? rows.length} total</span><Button variant="outline" size="sm" disabled>Pagination follows API response</Button></div></CardContent></Card> }
