'use client'

import useSWR from 'swr'
import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { pricingApi, adminMutationBody, auditHref, effectivePrice, formatAdminPrice, serverErrorMessage, validateTierOrder } from '@/lib/api/admin-pricing'
import type { AdminRow } from '@/lib/api/admin'

export function ReasonForm({ initial = {}, onSubmit, submitLabel = 'Save change' }: { initial?: Record<string, unknown>; onSubmit: (body: Record<string, unknown>) => Promise<void>; submitLabel?: string }) {
  const [values, setValues] = useState<Record<string, string>>(Object.fromEntries(Object.entries(initial).map(([key, value]) => [key, String(value ?? '')])))
  const [reason, setReason] = useState('')
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  async function save() { if (!reason.trim()) { setError('A reason is required for every configuration change.'); return }; setSaving(true); setError(''); try { await onSubmit(adminMutationBody(values, reason)); setReason('') } catch (caught) { setError(serverErrorMessage(caught)) } finally { setSaving(false) } }
  return <div className="flex flex-col gap-3">{Object.entries(values).map(([key, value]) => <label key={key} className="flex flex-col gap-1 text-sm"><span className="font-medium capitalize">{key.replaceAll('_', ' ')}</span><Input value={value} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} /></label>)}<label className="flex flex-col gap-1 text-sm"><span className="font-medium">Reason</span><Textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain why this live change is needed." /></label>{error ? <p className="text-sm text-destructive">{error}</p> : null}<Button onClick={() => void save()} disabled={saving}>{saving ? 'Saving…' : submitLabel}</Button></div>
}

function ConfigTable({ title, rows, columns, onEdit, showWeights = false }: { title: string; rows: AdminRow[]; columns: string[]; onEdit?: (row: AdminRow) => void; showWeights?: boolean }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><p className="text-sm text-muted-foreground">Changes apply to new quotes immediately. Papers already exported are unaffected.</p></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/30"><tr>{columns.map((column) => <th key={column} className="px-4 py-3 font-medium capitalize">{column.replaceAll('_', ' ')}</th>)}<th className="px-4 py-3">Audit</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b last:border-0"><td className="px-4 py-3 font-medium">{String(row.name ?? row.label ?? row.code ?? row.id)}</td>{columns.slice(1).map((column) => <td key={column} className="px-4 py-3">{showWeights && column === 'weight' ? <Badge variant="secondary">{String(row[column] ?? row.weight_units ?? '—')}</Badge> : column === 'price' ? formatAdminPrice(row[column]) : String(row[column] ?? '—')}</td>)}<td className="px-4 py-3"><Link className="text-primary underline-offset-4 hover:underline" href={auditHref(title.toLowerCase(), row.id)}>History</Link>{onEdit ? <Button variant="ghost" size="sm" className="ml-2" onClick={() => onEdit(row)}>Edit</Button> : null}</td></tr>)}</tbody></table></div></CardContent></Card> }

export function PricingManager() { const tiers = useSWR('admin-pricing-tiers', pricingApi.tiers); const packages = useSWR('admin-pricing-packages', pricingApi.packages); const weights = useSWR('admin-pricing-weights', pricingApi.weights); const rules = useSWR('admin-pricing-rules', pricingApi.rules); const features = useSWR('admin-pricing-features', pricingApi.features); const tierRows = tiers.data?.items ?? []; const orderWarning = tierRows.length > 1 && !validateTierOrder(tierRows); const [editing, setEditing] = useState<AdminRow | null>(null); const refresh = () => { void Promise.all([tiers.mutate(), packages.mutate(), weights.mutate(), rules.mutate(), features.mutate()]) }; return <div className="flex flex-col gap-6"><header><Badge variant="outline">Admin configuration</Badge><h1 className="mt-3 text-3xl font-semibold tracking-tight">Pricing & configuration</h1><p className="mt-2 text-sm text-muted-foreground">Changes apply to new quotes immediately. Papers already exported are unaffected.</p></header>{orderWarning ? <div className="rounded-md border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">Tier order is unsafe: sort order and internal capacity must increase together. Fix this before publishing a pricing change.</div> : null}<ConfigTable title="Paper-size tiers" rows={tierRows} columns={['name', 'max_mcq_count', 'max_cq_count', 'max_weight_units']} onEdit={setEditing} /><ConfigTable title="Packages" rows={packages.data?.items ?? []} columns={['name', 'quantity', 'price']} /><ConfigTable title="Question-type weights" rows={weights.data?.items ?? []} columns={['code', 'weight']} showWeights /><ConfigTable title="Advanced rules" rows={rules.data?.items ?? []} columns={['name', 'value']} /><ConfigTable title="Premium features" rows={features.data?.items ?? []} columns={['name', 'description', 'is_active']} />{editing ? <Card><CardHeader><CardTitle>Confirm tier change</CardTitle><p className="text-sm text-muted-foreground">Before/after changes require a reason and are recorded in audit history.</p></CardHeader><CardContent><ReasonForm initial={editing} onSubmit={async (body) => { await pricingApi.tier(editing.id, body); setEditing(null); refresh() }} /></CardContent></Card> : null}</div> }
