"use client"
import { useEffect, useState } from "react"
import { toast } from "sonner"
import { billingApi, money, type Pricing } from "@/lib/api/billing"
import { Button } from "@/components/ui/button"
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"

type Props = { open: boolean; onOpenChange: (open: boolean) => void; kind: "paper_export" | "template_extraction"; packageCode?: string; pricing?: Pricing; onComplete?: () => void }
export function CheckoutSheet({ open, onOpenChange, kind, packageCode, pricing, onComplete }: Props) {
 const [step, setStep] = useState<"summary"|"payment"|"waiting"|"done"|"failed">("summary"); const [busy,setBusy]=useState(false); const [purchaseId,setPurchaseId]=useState(""); const mode=process.env.NEXT_PUBLIC_PAYMENTS_MODE ?? "disabled"; const pkg=pricing?.paper_entitlement_packages.find((item)=>item.code===packageCode); const amount=kind==="template_extraction"?pricing?.template_extraction_standalone_price:pkg?.price_amount; const label=kind==="template_extraction"?"Template extraction":pkg?.display_name ?? "Paper export"
 useEffect(()=>{if(!open)setStep("summary")},[open]);
 async function buy(){setBusy(true);try{const result=await billingApi.purchase(kind==="paper_export"?"paper-export":"template-extraction",packageCode);setPurchaseId(result.purchase.id);if(mode==="mock")setStep("payment");else setStep("waiting")}catch(error){toast.error(error instanceof Error?error.message:"Purchase unavailable");setStep("failed")}finally{setBusy(false)}}
 async function mock(status:"succeeded"|"failed"){setBusy(true);try{await billingApi.mockWebhook(purchaseId,status);setStep(status==="succeeded"?"waiting":"failed");if(status==="succeeded"){setTimeout(()=>{setStep("done");onComplete?.()},1200)}}catch(error){toast.error(error instanceof Error?error.message:"Payments are not available yet")}finally{setBusy(false)}}
 return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent><SheetHeader><SheetTitle>{step==="done"?"Payment confirmed":label}</SheetTitle><SheetDescription>{step==="summary"?"One-time purchase. Prices are confirmed again before payment.":step==="payment"?"Simulated payment (development only)":"We never claim success until your entitlement is confirmed."}</SheetDescription></SheetHeader><div className="flex flex-col gap-4 py-6"><div className="rounded-lg border bg-muted/30 p-4"><p className="font-medium">{label}</p><p className="mt-1 text-2xl font-semibold">{amount===undefined?"—":money(amount)}</p><p className="text-sm text-muted-foreground">One-time purchase{kind==="paper_export"?" · Valid for this paper size only":""}</p></div>{step==="waiting"?<p className="text-sm">Waiting for entitlement confirmation…</p>:step==="failed"?<p className="text-sm text-destructive">Payment didn&apos;t go through. Nothing was added to your account.</p>:step==="done"?<p className="text-sm">Your entitlement was added.</p>:null}</div><SheetFooter>{step==="summary"&&<Button disabled={busy||mode==="disabled"||amount===undefined} onClick={buy}>{mode==="disabled"?"Purchasing opens soon":busy?"Starting…":"Confirm purchase"}</Button>}{step==="payment"&&<><Button variant="outline" disabled={busy} onClick={()=>void mock("failed")}>Fail</Button><Button disabled={busy} onClick={()=>void mock("succeeded")}>Pay</Button></>}{(step==="done"||step==="failed")&&<Button onClick={()=>onOpenChange(false)}>Continue</Button>}</SheetFooter></SheetContent></Sheet>
}
