"use client"

import { useEffect, useMemo, useState } from "react"
import useSWR from "swr"
import { BookOpenText, Check, ChevronLeft, ChevronRight, Filter, RotateCcw, Search, X } from "lucide-react"
import { PageContainer, PageHeader } from "@/components/shell/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { useAuth } from "@/components/auth/auth-provider"
import { questionApi, type QuestionSummary, type TaxonomyItem } from "@/lib/api/questions"

const emptyValue = "all"
const pageSize = 20
const mockQuestions: QuestionSummary[] = [
  { id: "mock-photosynthesis", question_text: "Explain how photosynthesis converts light energy into chemical energy in a green plant. Mention the role of chlorophyll and write the balanced word equation.", mark: 5, source: "sample", taxonomy: { class_id: "mock-class", class_name: "Class 10", subject_id: "mock-biology", subject_name: "Biology", question_type_id: "mock-creative", question_type_name: "Creative", level_name: "Application", chapter_name: "Life Processes", topic_name: "Photosynthesis" } },
  { id: "mock-quadratic", question_text: "If the roots of the equation x² − 7x + k = 0 differ by 3, find the value of k and verify both roots.", mark: 4, source: "sample", taxonomy: { class_id: "mock-class", class_name: "Class 10", subject_id: "mock-mathematics", subject_name: "Mathematics", question_type_id: "mock-short-answer", question_type_name: "Short answer", level_name: "Analysis", chapter_name: "Algebra", topic_name: "Quadratic equations" } },
]
type Filters = { classId: string; groupId: string; subjectId: string; chapterId: string; topicId: string; questionTypeId: string; levelId: string; sort: string }

function useTaxonomy(kind: string, params: Record<string, string | undefined>, enabled = true) {
  const key = enabled ? ["taxonomy", kind, ...Object.values(params)] : null
  return useSWR<TaxonomyItem[]>(key, ([, taxonomyKind]) => questionApi.taxonomy(taxonomyKind as string, params), { keepPreviousData: true })
}

function SelectFilter({ label, value, placeholder, options, disabled, onChange }: { label: string; value: string; placeholder: string; options?: TaxonomyItem[]; disabled?: boolean; onChange: (value: string | null) => void }) {
  return <div className="flex min-w-0 flex-1 flex-col gap-1.5"><Label className="text-xs font-medium text-muted-foreground">{label}</Label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="h-9 bg-background"><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent><SelectItem value={emptyValue}>All {label.toLowerCase()}</SelectItem>{options?.map((option) => <SelectItem key={option.id} value={option.id}>{option.name}</SelectItem>)}</SelectContent></Select></div>
}

function Filters({ filters, setFilter, classes, groups, subjects, chapters, topics, questionTypes, levels }: { filters: Filters; setFilter: (key: keyof Filters, value: string | null) => void; classes?: TaxonomyItem[]; groups?: TaxonomyItem[]; subjects?: TaxonomyItem[]; chapters?: TaxonomyItem[]; topics?: TaxonomyItem[]; questionTypes?: TaxonomyItem[]; levels?: TaxonomyItem[] }) {
  return <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><SelectFilter label="Class" value={filters.classId} placeholder="Choose class" options={classes} onChange={(v) => setFilter("classId", v)} /><SelectFilter label="Group / stream" value={filters.groupId} placeholder="Choose group" options={groups} disabled={filters.classId === emptyValue} onChange={(v) => setFilter("groupId", v)} /><SelectFilter label="Subject" value={filters.subjectId} placeholder="Choose subject" options={subjects} disabled={filters.classId === emptyValue} onChange={(v) => setFilter("subjectId", v)} /><SelectFilter label="Chapter" value={filters.chapterId} placeholder="Choose chapter" options={chapters} disabled={filters.subjectId === emptyValue} onChange={(v) => setFilter("chapterId", v)} /><SelectFilter label="Topic" value={filters.topicId} placeholder="Choose topic" options={topics} disabled={filters.chapterId === emptyValue} onChange={(v) => setFilter("topicId", v)} /><SelectFilter label="Question type" value={filters.questionTypeId} placeholder="Any type" options={questionTypes} onChange={(v) => setFilter("questionTypeId", v)} /><SelectFilter label="Level" value={filters.levelId} placeholder="Any level" options={levels} onChange={(v) => setFilter("levelId", v)} /></div>
}

function QuestionRow({ question, index, selected, expanded, onToggle, onExpand }: { question: QuestionSummary; index: number; selected: boolean; expanded: boolean; onToggle: () => void; onExpand: () => void }) {
  const { taxonomy } = question
  const path = [taxonomy.subject_name, taxonomy.chapter_name, taxonomy.topic_name].filter(Boolean).join(" · ")
  return <article className={`border-b border-border px-3 py-5 transition-colors sm:px-5 ${selected ? "border-l-2 border-l-primary bg-primary/[0.035]" : "border-l-2 border-l-transparent hover:bg-muted/40"}`}>
    <div className="flex items-start gap-3 sm:gap-5"><label className="mt-1 flex shrink-0 cursor-pointer items-center" aria-label={`Select question ${index}`}><input type="checkbox" checked={selected} onChange={onToggle} className="size-4 accent-primary" /></label><span className="hidden w-6 shrink-0 pt-0.5 font-mono text-xs text-muted-foreground sm:block">{String(index).padStart(2, "0")}</span><div className="min-w-0 flex-1"><button type="button" onClick={onExpand} aria-expanded={expanded} className="block w-full rounded-sm text-left text-[15px] font-medium leading-7 text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring">{question.question_text}</button>{expanded && <div className="mt-4 rounded-md border border-border bg-muted/35 p-3 text-sm leading-6 text-muted-foreground"><p>Preview is ready for this question. Full answer, explanation, and source details will appear here when the backend is connected.</p></div>}<div className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground"><span>{taxonomy.question_type_name}</span><span aria-hidden="true">·</span><span>{question.mark} {question.mark === 1 ? "mark" : "marks"}</span>{taxonomy.level_name && <><span aria-hidden="true">·</span><span>{taxonomy.level_name}</span></>}{path && <><span aria-hidden="true">·</span><span className="truncate">{path}</span></>}{question.source === "sample" && <Badge variant="outline" className="ml-1 h-5 text-[10px]">Sample</Badge>}</div></div><div className="flex shrink-0 items-center gap-1"><Button variant="ghost" size="sm" onClick={onExpand} className="hidden sm:inline-flex">{expanded ? "Hide" : "Preview"}</Button><Button variant={selected ? "secondary" : "outline"} size="sm" onClick={onToggle} aria-label={`${selected ? "Remove" : "Add"} question ${index}`}>{selected ? <Check data-icon="inline-start" /> : null}<span className="hidden sm:inline">{selected ? "Added" : "Add"}</span></Button></div></div>
  </article>
}

function LoadingRows() { return <div className="divide-y divide-border">{[1, 2, 3, 4].map((item) => <div key={item} className="flex gap-4 px-5 py-6"><div className="size-4 rounded-sm bg-muted" /><div className="flex flex-1 flex-col gap-3"><div className="h-4 w-4/5 rounded bg-muted" /><div className="h-3 w-2/5 rounded bg-muted" /></div></div>)}</div> }

export default function QuestionBankPage() {
  const { configured } = useAuth()
  const [language, setLanguage] = useState<"en" | "bn">("en")
  const [filters, setFilters] = useState<Filters>({ classId: emptyValue, groupId: emptyValue, subjectId: emptyValue, chapterId: emptyValue, topicId: emptyValue, questionTypeId: emptyValue, levelId: emptyValue, sort: "newest" })
  const [query, setQuery] = useState("")
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<QuestionSummary[]>([])
  const [expandedId, setExpandedId] = useState<string | null>(null)
  useEffect(() => { const sync = () => setLanguage(window.localStorage.getItem("qtor-language") === "bn" ? "bn" : "en"); sync(); window.addEventListener("qtor-language-change", sync); return () => window.removeEventListener("qtor-language-change", sync) }, [])
  const params = { class_id: filters.classId === emptyValue ? undefined : filters.classId }
  const classes = useTaxonomy("classes", {}); const groups = useTaxonomy("groups", { class_id: params.class_id }, Boolean(params.class_id)); const subjects = useTaxonomy("subjects", { class_id: params.class_id, group_id: filters.groupId === emptyValue ? undefined : filters.groupId }, Boolean(params.class_id)); const chapters = useTaxonomy("chapters", { subject_id: filters.subjectId === emptyValue ? undefined : filters.subjectId }, filters.subjectId !== emptyValue); const topics = useTaxonomy("topics", { chapter_id: filters.chapterId === emptyValue ? undefined : filters.chapterId }, filters.chapterId !== emptyValue); const questionTypes = useTaxonomy("question-types", {}); const levels = useTaxonomy("levels", {})
  const questionParams = useMemo(() => ({ class_id: params.class_id, group_id: filters.groupId === emptyValue ? undefined : filters.groupId, subject_id: filters.subjectId === emptyValue ? undefined : filters.subjectId, chapter_id: filters.chapterId === emptyValue ? undefined : filters.chapterId, topic_id: filters.topicId === emptyValue ? undefined : filters.topicId, question_type_id: filters.questionTypeId === emptyValue ? undefined : filters.questionTypeId, level_id: filters.levelId === emptyValue ? undefined : filters.levelId, q: query || undefined, sort: filters.sort, page, page_size: pageSize }), [filters, query, page, params.class_id])
  const questions = useSWR(["questions", questionParams], ([, values]) => questionApi.questions(values), { keepPreviousData: true })
  const setFilter = (key: keyof Filters, value: string | null) => { setPage(1); setFilters((current) => { const next = { ...current, [key]: value ?? emptyValue }; if (key === "classId") Object.assign(next, { groupId: emptyValue, subjectId: emptyValue, chapterId: emptyValue, topicId: emptyValue }); if (key === "groupId" || key === "subjectId") Object.assign(next, { chapterId: emptyValue, topicId: emptyValue }); if (key === "chapterId") next.topicId = emptyValue; return next }) }
  const toggle = (question: QuestionSummary) => setSelected((current) => current.some((item) => item.id === question.id) ? current.filter((item) => item.id !== question.id) : [...current, question])
  const reset = () => { setFilters({ classId: emptyValue, groupId: emptyValue, subjectId: emptyValue, chapterId: emptyValue, topicId: emptyValue, questionTypeId: emptyValue, levelId: emptyValue, sort: "newest" }); setQuery(""); setPage(1); setExpandedId(null) }
  const previewMode = !configured || !questions.data
  const items = questions.data?.items?.length ? questions.data.items : previewMode ? mockQuestions : []
  const total = questions.data?.total ?? (previewMode ? mockQuestions.length : 0)
  const totalPages = questions.data?.total_pages ?? (total ? Math.ceil(total / pageSize) : 1)
  const activeFilters = Object.entries(filters).some(([key, value]) => key !== "sort" && value !== emptyValue) || Boolean(query)

  return <PageContainer><PageHeader title={language === "bn" ? "প্রশ্ন ব্যাংক" : "Question Bank"} description={language === "bn" ? "আপনার লাইব্রেরি থেকে দ্রুত সঠিক প্রশ্নটি খুঁজুন।" : "Find, review, and select questions for your papers."} actions={<><Button variant="outline" onClick={reset}><RotateCcw data-icon="inline-start" />Reset</Button><Button disabled={!selected.length}><BookOpenText data-icon="inline-start" />Add {selected.length ? `${selected.length} to paper` : "to paper"}</Button></>} />
    <div className="flex flex-col gap-5"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder={language === "bn" ? "প্রশ্ন খুঁজুন..." : "Search questions..."} className="h-11 pl-9 text-sm" /></div>
      <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-medium"><span>Filters</span><span className="text-xs text-muted-foreground">Narrow by hierarchy and type</span></div><Sheet><SheetTrigger><span className="inline-flex h-9 items-center gap-2 rounded-md border border-input bg-background px-3 text-sm font-medium lg:hidden"><Filter data-icon="inline-start" />Filters</span></SheetTrigger><SheetContent side="bottom" className="max-h-[85vh] overflow-y-auto"><SheetHeader><SheetTitle>Filter questions</SheetTitle></SheetHeader><div className="mt-5"><Filters filters={filters} setFilter={setFilter} classes={classes.data} groups={groups.data} subjects={subjects.data} chapters={chapters.data} topics={topics.data} questionTypes={questionTypes.data} levels={levels.data} /></div></SheetContent></Sheet></div>
      <div className="hidden rounded-md border border-border bg-card p-4 lg:block"><Filters filters={filters} setFilter={setFilter} classes={classes.data} groups={groups.data} subjects={subjects.data} chapters={chapters.data} topics={topics.data} questionTypes={questionTypes.data} levels={levels.data} /></div>
      <div className="flex items-center justify-between border-b border-border pb-3 text-sm"><div className="flex items-center gap-3"><span className="font-medium">{total.toLocaleString()} questions</span>{previewMode && <Badge variant="outline">Preview data</Badge>}</div><Button variant="ghost" size="sm" onClick={() => setSelected((current) => [...current, ...items.filter((item) => !current.some((selectedItem) => selectedItem.id === item.id))])} disabled={!items.length}>Select visible</Button></div>
      <section className="overflow-hidden rounded-md border border-border bg-card" aria-label="Question list">{questions.isLoading && !previewMode ? <LoadingRows /> : questions.error && configured ? <Empty className="min-h-64"><EmptyHeader><EmptyMedia variant="icon"><RotateCcw /></EmptyMedia><EmptyTitle>Unable to load questions</EmptyTitle><EmptyDescription>{questions.error instanceof Error ? questions.error.message : "Please try again."}</EmptyDescription></EmptyHeader><Button onClick={() => questions.mutate()}>Retry</Button></Empty> : !items.length ? <Empty className="min-h-64"><EmptyHeader><EmptyMedia variant="icon"><Search /></EmptyMedia><EmptyTitle>No questions found</EmptyTitle><EmptyDescription>Try changing your search or filters.</EmptyDescription></EmptyHeader>{activeFilters && <Button variant="outline" onClick={reset}><X data-icon="inline-start" />Clear filters</Button>}</Empty> : <div>{items.map((question, index) => <QuestionRow key={question.id} question={question} index={(page - 1) * pageSize + index + 1} selected={selected.some((item) => item.id === question.id)} expanded={expandedId === question.id} onToggle={() => toggle(question)} onExpand={() => setExpandedId((current) => current === question.id ? null : question.id)} />)}</div>}</section>
      {totalPages > 1 && <div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">Page {page} of {totalPages}</p><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1}><ChevronLeft data-icon="inline-start" />Previous</Button><Button variant="outline" size="sm" onClick={() => setPage((current) => Math.min(totalPages, current + 1))} disabled={page >= totalPages}>Next<ChevronRight data-icon="inline-end" /></Button></div></div>}
    </div>{selected.length > 0 && <div className="fixed inset-x-3 bottom-20 z-20 flex items-center justify-between gap-3 rounded-md border border-primary/20 bg-card px-4 py-3 shadow-lg sm:inset-x-auto sm:bottom-6 sm:right-6 sm:w-auto"><p className="text-sm font-medium">{selected.length} selected</p><div className="flex items-center gap-2"><Button variant="ghost" size="sm" onClick={() => setSelected([])}><X data-icon="inline-start" />Clear</Button><Button size="sm"><BookOpenText data-icon="inline-start" />Add to paper</Button></div></div>}</PageContainer>
}

